### ISSUE TITLE
Bug with ARB - rejecting cards that expire in Jan-Apr of 2020 if you pass it as '04/20'

### ISSUE THREAD

**Issue by dmitrypol** [AuthorizeNet/sdk-ruby#44] opened 2015-05-18 16:52 UTC
We identified a bug with ARB API rejecting credit cards that expire in January, February, March or April of years well into future.  

This only happens if you pass expiration date as '04/20'.  ARB works if you pass '0420'.  But if you pass '05/20' than ARB also works.  Donations also work if you pass '04/20'.  Would be nice to fix to make system consistent.  

Repro steps:
Create subscription when credit card expiring in January, February, March or April of 2020
ARB responds with:  response_code = Error, response_reason_code = E00013, response_reason_text = The credit card has expired.
It works for May - December expiration dates.  We tested this with various credit cards in sandbox and production, for years till 2025.  
According to http://developer.authorize.net/tools/arberrorcodes/ E00013 means "The field is invalid"

**Comment by brianmc** [comment] 2015-05-19 00:13
We're looking into this issue as a high priority.

**Comment by brianmc** [comment] 2015-05-22 06:07
Hi @dmitrypol, we're struggling to reproduce this.  Can you send some simple sample code to developer@authorize.net which consistently reproduces?

Many Thanks,

Brian

**Comment by dmitrypol** [comment] 2015-05-22 17:11
Hi Brian

Here is my code.  Pass expiration date of '04/16', '01/20, '03/18' and it will fail with "card expired" message.  It will work for '06/15' or '08/18'.  If you remove / it will work for '0216'.

I just tested it against sandbox and it responded with "response_code = Error, response_reason_code = E00013, response_reason_text = The credit card has expired."

I am using 1.8.3 authorize_net gem with the patch for issue 39.  

transaction = AuthorizeNet::ARB::Transaction.new(cc_proc_login, cc_proc_key, gateway: credit_card_processor_gateway)
    customer = {
      email: user.email,
      first_name: user.first_name,
      last_name: user.last_name,
      description: campaign.slug,
      invoice_num: id.to_s[0..19],
      cust_id: user.id.to_s[0..19]
    }
    transaction.set_customer(customer)    
    credit_card = AuthorizeNet::CreditCard.new(self.card_number, self.card_expiration, card_code: self.card_code)
    subscription = AuthorizeNet::ARB::Subscription.new(
      :name => "#{campaign.slug}",
      :length => interval_to_auth_net_length(self.interval),
      :unit => :month,
      :start_date => start_date,
      :total_occurrences => total_occurrences,
      :amount => self.amount,
      :credit_card => credit_card,
    )
response = transaction.create(subscription)

**Comment by brianmc** [comment] 2015-05-31 15:17
Hi @dmitrypol 

So the issue is with passing a slash in the date.  it's not supported but as you say there are some dates that get through - just by luck.

In the file lib/authorize_net/xml_transaction.rb you can see at line 224 it's converting the dates from the sdk format MMYY.  If that fails (e.g. because there is a slash) the next code line attempts to get a date out anyway, by doing a simple parse.  This is the line that's causing the problem, because 04/16 is parsed in ruby as 2015-04-16 (year defaults to current!!) then the format uses the year and month and passes it through to the API as 2015-04 .... an expired date.

Thanks again for reporting this issue, we'll be providing a fix in the upcoming release.  Ideally we'd like to remove the non-deterministic code that is "attempting" to parse any string passed but we need to be careful there because it could be "working" for some client input.

**Comment by brianmc** [comment] 2015-06-01 04:32
Hi @dmitrypol,

We've tried out a few changes but I think the best thing here is to stick with the documented format of MMYY.  I'm not sure if you have a requirement to use MM/YY but a simple gsub would strip that out on your end.  We'll certainly keep looking at alternatives as you have uncovered an issue for sure but we are not currently planing any changes in this release.

Brian

**Comment by dmitrypol** [comment] 2015-06-01 15:04
Hi Brian
Yes, that's what I am doing gsub('/','').  The reason I was going with MM/YY is because I saw a code sample somewhere else.  Later I after I fixed it I saw a MMYY reference in your code.  So yes, I should have read the docs more carefully but it would be nice to have consistency.

**Comment by brianmc** [comment] 2015-06-01 19:15
Absolutely, we should have consistency and there should be no way for some dates in a specific format to fail while other dates in the same format pass.

I'm going to close this one if you don't mind and create 2 internal issues, one for officially deprecating acceptance of other formats and one for better documentation.

Thanks again for the great feedback,

Brian

**Closed by brianmc** 2015-06-01 19:15 UTC
