### ISSUE TITLE
unable to access few parameters like  response.amount, response.method

### ISSUE THREAD

**Issue by rahulgoutham** [AuthorizeNet/sdk-ruby#52] opened 2015-10-03 11:47 UTC
Sorry my issue got posted twise.

response is this 
 

#<AuthorizeNet::AIM::Response:0xb00c354
 @custom_fields={},
 @fields=
  {:response_code=>"1",
   :response_subcode=>"1",
   :response_reason_code=>"1",
   :response_reason_text=>"This transaction has been approved.",
   :authorization_code=>"9VHMMC",
   :avs_response=>"Y",
   :transaction_id=>"2241516704",
   :invoice_number=>"",
   :description=>"",
   :amount=>#<BigDecimal:b0079d0,'0.1E2',9(18)>,
   :method=>"CC",
   :transaction_type=>"auth_capture",
   :customer_id=>"",
   :first_name=>"",
   :last_name=>"",
   :company=>"",
   :address=>"",
   :city=>"",
   :state=>"",
   :zip_code=>"",
   :country=>"",
   :phone=>"",
   :fax=>"",
   :email_address=>"",
   :ship_to_first_name=>"",
   :ship_to_last_name=>"",
   :ship_to_company=>"",
   :ship_to_address=>"",
   :ship_to_city=>"",
   :ship_to_state=>"",
   :ship_to_zip_code=>"",
   :ship_to_country=>"",
   :tax=>#<BigDecimal:b0079a8,'0.0',9(9)>,
   :duty=>#<BigDecimal:b00796c,'0.0',9(9)>,
   :freight=>#<BigDecimal:b007930,'0.0',9(9)>,
   :tax_exempt=>"",
   :purchase_order_number=>"",
   :md5_hash=>"something",
   :card_code_response=>"",
   :cardholder_authentication_verification_response=>"2",
   :account_number=>"XXXX0002",
   :card_type=>"American Express"},
 @raw_response=#<Net::HTTPOK 200 OK readbody=true>,
 @transaction=
  #<AuthorizeNet::AIM::Transaction:0xb02cb7c
   @allow_split_transaction=false,
   @api_login_id="my_id",
   @api_transaction_key=" my_key",
   @cp_version=nil,
   @custom_fields={},
   @delimiter=",",
   @device_type=1,
   @encapsulation_character=nil,
   @fields={:method=>"CC", :card_num=>"370000000000002", :exp_date=>"1120", :amount=>"10.00"},
   @gateway="https://test.authorize.net/gateway/transact.dll",
   @market_type=2,
   @response=#<AuthorizeNet::AIM::Response:0xb00c354 ...>,
   @test_mode=false,
   @type="AUTH_CAPTURE",
   @verify_ssl=false,
   @version="3.1">,
 @version="3.1">

I'm unable to use amount which I got from response. 
response.amount
NoMethodError: undefined method `amount' for #<AuthorizeNet::AIM::Response:0xb00c354>

**Comment by brianmc** [comment] 2015-10-13 04:41
Closing as a dupe of #53

**Closed by brianmc** 2015-10-13 04:41 UTC
